package info.interactivesystems.gamificationengine.entities.rewards;

import info.interactivesystems.gamificationengine.dao.GoalDAO;
import info.interactivesystems.gamificationengine.dao.RuleDAO;
import info.interactivesystems.gamificationengine.entities.Organisation;
import info.interactivesystems.gamificationengine.entities.Player;
import info.interactivesystems.gamificationengine.entities.PlayerGroup;
import info.interactivesystems.gamificationengine.entities.goal.Goal;

import java.util.List;

import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

/**
 * The super class of all rewards. Here are general information of the reward
 * like to which organisation the reward belongs to.
 *
 */
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "REWARD_TYPE", discriminatorType = DiscriminatorType.STRING)
public abstract class Reward {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	@NotNull
	@ManyToOne
	private Organisation belongsTo;

	private int timeToLive;

	@ManyToMany(mappedBy = "rewards")
	List<Goal> goals;

	public abstract void addReward(Player player, GoalDAO goalDao, RuleDAO ruleDao);

	public abstract void addReward(PlayerGroup group, GoalDAO goalDao, RuleDAO ruleDao);

	/**
	 * Get the id of the reward which was generated by the creation.
	 * 
	 * @return id as int
	 */
	public int getId() {
		return id;
	}

	/**
	 * Set the id of the reward.
	 * 
	 * @param id
	 *            of the reward
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Get the organisation the reward belongs to.
	 * 
	 * @return a not nullable organisation
	 */
	public Organisation getBelongsTo() {
		return belongsTo;
	}

	/**
	 * Set the organisation to which this reward belongs, may not be null.
	 * 
	 * @param belongsTo
	 *            an organisation
	 */
	public void setBelongsTo(Organisation belongsTo) {
		this.belongsTo = belongsTo;
	}

	public int getTimeToLive() {
		return timeToLive;
	}

	public void setTimeToLive(int timeToLive) {
		this.timeToLive = timeToLive;
	}

	/**
	 * Test if a group belongs to a specific organisation.
	 */
	public boolean belongsTo(Organisation organisation) {
		return getBelongsTo().getApiKey().equals(organisation.getApiKey());
	}

}
